// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import LeftPannel from "@/left/LeftPannel";
// import { Box } from "@mui/material";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//   children2,
// }: Readonly<{
//   children: React.ReactNode;
//   children2: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Box display="flex" width="100%" height="100vh" border="none">
//           {/* Left Container */}
//           <Box
//             width="21.4%" 
//             height="100vh"
//             py={2}
//           >
//             <LeftPannel />
//           </Box>

//           <Box
//             width="25%"
//             bgcolor="#1c1c1c"
//             height="100vh"
//             px={2}
//             py={2}
//             sx={{
//               overflowY: "auto",
//               scrollbarWidth: "none",
//               "&::-webkit-scrollbar": { display: "none" },
//             }}
//           >
//             {children}
//           </Box>

//           <Box width="53.6%" height="100vh" overflow="auto" px={2}>
//             {children2}
//           </Box>
//         </Box>
//       </body>
//     </html>
//   );
// }



//----------------------------------------------------------


"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftPannel from "@/left/LeftPannel";
import { Box } from "@mui/material";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        <QueryClientProvider client={queryClient}>
          <Box display="flex" width="100%" height="100vh" border="none">
            <Box width="21.4%" height="100vh">
              <LeftPannel />
            </Box>

            {children}
          </Box>
        </QueryClientProvider>
      </body>
    </html>
  );
}
